directories:
    output: setup-${arch}
    buildResources: dist

afterSign: scripts/notarize.js
files:
    - dist/*.js
    - dist/*.css
    - css/*.css
    - pages/**/*
    - icons/**/*
    - icons/*.svg
    - js/**/*
    - ./main.build.js
    - ext/**/*
    - index.html
    - server-config.js
    - api/*
    - img/*.jpg
    - img/*.jpeg
    - reader/*
    - resources/**/*
dmg:
    sign: false

win:
    extraResources:
        - from: res
          to: res
          filter:
            - "**/*"
    icon: ./icons/logowin.ico
    target:
        - target: nsis
        - target: zip
    publish:
        - provider : generic
          url: http://d.xiangtian.ren/update/browser/win/
          channel: latest

mac:
    entitlements: entitlements.mac.plist
    entitlementsInherit: entitlements.mac.plist
    hardenedRuntime: true
    gatekeeperAssess: false
    icon: ./icons/icon.icns
    category: public.app-category.utilities
    target:
        - target: dmg
        - target: zip
    publish:
      - provider : generic
        url: http://d.xiangtian.ren/update/browser/mac-${arch}/
        channel: latest


nsis:
    allowToChangeInstallationDirectory: true
    oneClick: false
    perMachine: true
protocols:
    name: TSBrowser
    schemes:
       - tsb


