directories:
    output: dist
    buildResources: bundle

files:
    - bundle/**/*.js
    - styles/**/*.css
    - ./*.html
    - img/**/*
    - assets/**/*

win:
    icon: ./img/icons/win/icon-black.ico
    target:
        - target: nsis
          arch:
              - x64
              - ia32
        - target: zip
          arch:
              - x64
              - ia32
    publish:
        - github

mac:
    icon: ./img/icons/mac/icon-white-circle.icns
    category: public.app-category.utilities
    target:
        - dmg
        - zip
    publish:
        - github

nsis:
    allowToChangeInstallationDirectory: true
    oneClick: false
    perMachine: true
